kind = "web"
previewPath = "/"
title = "MyPortofolio"
version = "1.0.0"
id = "artifacts/portfolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21114

[services.development]
run = "pnpm --filter @workspace/myportofolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/myportofolio", "run", "build" ]
publicDir = "artifacts/myportofolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21114"
BASE_PATH = "/"
